fix: Change NUI callback URLs from http to https
Fixed Mixed Content error caused by NUI page being loaded over HTTPS
but callbacks using HTTP protocol.

Error: 'The page at https://cfx-nui-rcon/nui/index.html was loaded
over HTTPS, but requested an insecure XMLHttpRequest endpoint'

Changed all callbacks from http://zcon/ to https://zcon/:
- closeUI
- placeOrder
- startDelivery
- withdrawMoney
- depositMoney

This fixes compatibility with FiveM's secure NUI implementation.